Add storage explorer link for transfers to Azure Storage containers
agera-edc/EDCDataDashboard pull request #12
Opened 2022-05-04 13:31 UTC by marcgs

Add storage explorer link to previous transfer list to visualize results:
- Button only present for AzureStorage transfers
- Storage explorer link in app.config.json of the form `storageexplorer://v=1&accountid=/subscriptions/{{subscription}}/resourceGroups/{{resourceGroup}}/providers/Microsoft.Storage/storageAccounts/{{account}}&subscriptionid={{subscriptionId}}&resourcetype=Azure.BlobContainer&resourcename={{container}}`
  - `account` and `container` are retrieved for each transfer process
  - the rest of variables are provided at provisioning time with terraform

2022-05-05 08:01 UTC, chrislomonico requested changes

2022-05-05 08:03 UTC, marcgs commented on src/assets/config/app.config.json
> +  "storageExplorerLinkTemplate": "storageexplorer://v=1&accountid=/subscriptions/{{subscription}}/resourceGroups/{{resourceGroup}}/providers/Microsoft.Storage/storageAccounts/{{account}}&subscription
Yep, I will correct this. If has no impact as this file is just for exemplary reasons though. On deploy it gets generated correctly by terraform here: https://github.com/agera-edc/MinimumViableDataspace/pull/98/files

2022-05-05 08:28 UTC, marcgs commented on src/assets/config/app.config.json
> +  "storageExplorerLinkTemplate": "storageexplorer://v=1&accountid=/subscriptions/{{subscription}}/resourceGroups/{{resourceGroup}}/providers/Microsoft.Storage/storageAccounts/{{account}}&subscription
Fixed @chrislomonico

2022-05-05 14:15 UTC, paullatzelsperger reviewed
This seems to require Azure Storage Explorer to be installed - is there a way to generate a link that opens in the browser?

2022-05-05 14:26 UTC, marcgs commented
> This seems to require Azure Storage Explorer to be installed - is there a way to generate a link that opens in the browser?

There is the possibility of generating a link with a SAS token with a URL leading to the Azure portal, but this would be a security risk as we can not guarantee the person using the app has permissions to see the transferred files. The storage explorer has authentication on its own, so we make sure only authorized users can see them.

2022-05-06 09:19 UTC, chrislomonico approved these changes
Requested change completed, approving

2022-05-06 11:35 UTC, marcgs commented
@paullatzelsperger implemented an info box at the top to indicate that Azure Storage Explorer needs to be installed.
<img width="1609" alt="Screenshot 2022-05-06 at 13 34 13" src="https://user-images.githubusercontent.com/5342234/167123933-fbdd82fa-5923-4b70-a130-2a5df473a212.png">

2022-05-06 12:17 UTC, cpeeyush approved these changes

2022-05-06 12:44 UTC, paullatzelsperger approved these changes

2022-05-06 12:47 UTC, merged