Diverse renamings prior to #16
agera-edc/EDCDataDashboard pull request #23
Opened 2022-05-09 12:26 UTC by marcgs

Diverse renamings prior to implementation of #16

2022-05-09 14:31 UTC, chrislomonico requested changes
one naming change seems off; granted this is only from reading through it.  I will run it locally to confirm

2022-05-09 14:31 UTC, chrislomonico commented on src/modules/app/app-routing.module.ts
> +    path: 'contractdefinition-viewer',
should this be update to `contract-definition-viewer`?

2022-05-09 15:18 UTC, cpeeyush approved these changes

2022-05-09 17:40 UTC, paullatzelsperger commented
one minor thing, ready to merge once that's resolved.

2022-05-10 05:33 UTC, merged

2022-05-10 05:33 UTC, marcgs commented
Merging as @chrislomonico comment has been addressed